# Generated by Django 4.2.3 on 2023-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='custom_shortcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
